//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestovyjjProekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "Название as \'Название\'"})]
    [View("КлиентL", new string[] {
            "Название as \'Название\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Название CustomAttributes)

        // *** End programmer edit section *** (Клиент.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Название Get start)

                // *** End programmer edit section *** (Клиент.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Клиент.Название Get end)

                // *** End programmer edit section *** (Клиент.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Название Set start)

                // *** End programmer edit section *** (Клиент.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Клиент.Название Set end)

                // *** End programmer edit section *** (Клиент.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.TestovyjjProekt.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.TestovyjjProekt.Клиент));
                }
            }
        }
    }
}
