//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestovyjjProekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Продажа.
    /// </summary>
    // *** Start programmer edit section *** (Продажа CustomAttributes)

    // *** End programmer edit section *** (Продажа CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПродажаE", new string[] {
            "Дата as \'Дата\'",
            "Клиент as \'Клиент\'",
            "Клиент.Название as \'Название\'"}, Hidden=new string[] {
            "Клиент.Название"})]
    [AssociatedDetailViewAttribute("ПродажаE", "Строка", "СтрокаE", true, "", "Строка", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПродажаE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("ПродажаL", new string[] {
            "Дата as \'Дата\'",
            "Клиент.Название as \'Название\'"})]
    public class Продажа : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.TestovyjjProekt.Клиент fКлиент;
        
        private IIS.TestovyjjProekt.DetailArrayOfСтрока fСтрока;
        
        // *** Start programmer edit section *** (Продажа CustomMembers)

        // *** End programmer edit section *** (Продажа CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Продажа.Дата CustomAttributes)

        // *** End programmer edit section *** (Продажа.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Продажа.Дата Get start)

                // *** End programmer edit section *** (Продажа.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Продажа.Дата Get end)

                // *** End programmer edit section *** (Продажа.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажа.Дата Set start)

                // *** End programmer edit section *** (Продажа.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Продажа.Дата Set end)

                // *** End programmer edit section *** (Продажа.Дата Set end)
            }
        }
        
        /// <summary>
        /// Продажа.
        /// </summary>
        // *** Start programmer edit section *** (Продажа.Клиент CustomAttributes)

        // *** End programmer edit section *** (Продажа.Клиент CustomAttributes)
        [NotNull()]
        public virtual IIS.TestovyjjProekt.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Продажа.Клиент Get start)

                // *** End programmer edit section *** (Продажа.Клиент Get start)
                IIS.TestovyjjProekt.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Продажа.Клиент Get end)

                // *** End programmer edit section *** (Продажа.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажа.Клиент Set start)

                // *** End programmer edit section *** (Продажа.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Продажа.Клиент Set end)

                // *** End programmer edit section *** (Продажа.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Продажа.
        /// </summary>
        // *** Start programmer edit section *** (Продажа.Строка CustomAttributes)

        // *** End programmer edit section *** (Продажа.Строка CustomAttributes)
        public virtual IIS.TestovyjjProekt.DetailArrayOfСтрока Строка
        {
            get
            {
                // *** Start programmer edit section *** (Продажа.Строка Get start)

                // *** End programmer edit section *** (Продажа.Строка Get start)
                if ((this.fСтрока == null))
                {
                    this.fСтрока = new IIS.TestovyjjProekt.DetailArrayOfСтрока(this);
                }
                IIS.TestovyjjProekt.DetailArrayOfСтрока result = this.fСтрока;
                // *** Start programmer edit section *** (Продажа.Строка Get end)

                // *** End programmer edit section *** (Продажа.Строка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажа.Строка Set start)

                // *** End programmer edit section *** (Продажа.Строка Set start)
                this.fСтрока = value;
                // *** Start programmer edit section *** (Продажа.Строка Set end)

                // *** End programmer edit section *** (Продажа.Строка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПродажаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродажаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродажаE", typeof(IIS.TestovyjjProekt.Продажа));
                }
            }
            
            /// <summary>
            /// "ПродажаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродажаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродажаL", typeof(IIS.TestovyjjProekt.Продажа));
                }
            }
        }
    }
}
