//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestovyjjProekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Строка.
    /// </summary>
    // *** Start programmer edit section *** (Строка CustomAttributes)

    // *** End programmer edit section *** (Строка CustomAttributes)
    [AutoAltered()]
    [Caption("Строка товара")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтрокаE", new string[] {
            "Колич as \'Колич\'",
            "Товар as \'Товар\'",
            "Товар.Название as \'Название\'"}, Hidden=new string[] {
            "Товар.Название"})]
    [MasterViewDefineAttribute("СтрокаE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class Строка : ICSSoft.STORMNET.DataObject
    {
        
        private int fКолич;
        
        private IIS.TestovyjjProekt.Товар fТовар;
        
        private IIS.TestovyjjProekt.Продажа fПродажа;
        
        // *** Start programmer edit section *** (Строка CustomMembers)

        // *** End programmer edit section *** (Строка CustomMembers)

        
        /// <summary>
        /// Колич.
        /// </summary>
        // *** Start programmer edit section *** (Строка.Колич CustomAttributes)

        // *** End programmer edit section *** (Строка.Колич CustomAttributes)
        public virtual int Колич
        {
            get
            {
                // *** Start programmer edit section *** (Строка.Колич Get start)

                // *** End programmer edit section *** (Строка.Колич Get start)
                int result = this.fКолич;
                // *** Start programmer edit section *** (Строка.Колич Get end)

                // *** End programmer edit section *** (Строка.Колич Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Строка.Колич Set start)

                // *** End programmer edit section *** (Строка.Колич Set start)
                this.fКолич = value;
                // *** Start programmer edit section *** (Строка.Колич Set end)

                // *** End programmer edit section *** (Строка.Колич Set end)
            }
        }
        
        /// <summary>
        /// Строка.
        /// </summary>
        // *** Start programmer edit section *** (Строка.Товар CustomAttributes)

        // *** End programmer edit section *** (Строка.Товар CustomAttributes)
        [NotNull()]
        public virtual IIS.TestovyjjProekt.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (Строка.Товар Get start)

                // *** End programmer edit section *** (Строка.Товар Get start)
                IIS.TestovyjjProekt.Товар result = this.fТовар;
                // *** Start programmer edit section *** (Строка.Товар Get end)

                // *** End programmer edit section *** (Строка.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Строка.Товар Set start)

                // *** End programmer edit section *** (Строка.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Строка.Товар Set end)

                // *** End programmer edit section *** (Строка.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.TestovyjjProekt.Продажа.
        /// </summary>
        // *** Start programmer edit section *** (Строка.Продажа CustomAttributes)

        // *** End programmer edit section *** (Строка.Продажа CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.TestovyjjProekt.Продажа Продажа
        {
            get
            {
                // *** Start programmer edit section *** (Строка.Продажа Get start)

                // *** End programmer edit section *** (Строка.Продажа Get start)
                IIS.TestovyjjProekt.Продажа result = this.fПродажа;
                // *** Start programmer edit section *** (Строка.Продажа Get end)

                // *** End programmer edit section *** (Строка.Продажа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Строка.Продажа Set start)

                // *** End programmer edit section *** (Строка.Продажа Set start)
                this.fПродажа = value;
                // *** Start programmer edit section *** (Строка.Продажа Set end)

                // *** End programmer edit section *** (Строка.Продажа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтрокаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтрокаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтрокаE", typeof(IIS.TestovyjjProekt.Строка));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Строка.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСтрока CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСтрока CustomAttributes)
    public class DetailArrayOfСтрока : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.TestovyjjProekt.DetailArrayOfСтрока members)

        // *** End programmer edit section *** (IIS.TestovyjjProekt.DetailArrayOfСтрока members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Строка by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Строка.
        /// </summary>
        public DetailArrayOfСтрока(IIS.TestovyjjProekt.Продажа fПродажа) : 
                base(typeof(Строка), ((ICSSoft.STORMNET.DataObject)(fПродажа)))
        {
        }
        
        public IIS.TestovyjjProekt.Строка this[int index]
        {
            get
            {
                return ((IIS.TestovyjjProekt.Строка)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.TestovyjjProekt.Строка dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
